lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - ".github/"
  - "dsa/"
  - ".gitignore"
  - ".python-version"
  - "pyproject.toml"
  - "uv.lock"
  - "README.md"
  - ".env"
  - "asttest.py"
  - "main.py"
  - "folder_structure.txt"
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Neural Notes"
description: "You can find notes related to various machine learning and deep learning topics including knowledge about various tools and frameworks."
collections:
  notes:
    output: true
    permalink: /notes/:path/