lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude: [".github/","dsa/",".gitignore",".python-version","pyproject.toml","uv.lock","README.md"]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: Neutral Notes
description: You can find notes related to various machine learning and deep learning topics including knowledge about various tools and frameworks.