source "https://rubygems.org"

gem "jekyll-theme-chirpy", "~> 7.0"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-redirect-from"
  gem "jekyll-seo-tag"
  gem "jekyll-archives"
  gem "jekyll-sitemap"
end

group :test do
  gem "html-proofer", "~> 5.0"
end
